<%-- 
    Document   : datajsp
    Created on : Feb 15, 2012, 9:13:20 AM
    Author     : Misha
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>



        <div><h1>this data was generated by datajsp </h1>
            <img src="../images/ctrol.png" width="40" height="40" />
        
        </div>
        

